# Generated by Django 4.2.2 on 2023-09-13 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='applicantSignatureImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant_signature', to='blog.signaturemodel'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierSignatureImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_signature', to='blog.signaturemodel'),
        ),
    ]
