# Generated by Django 4.2.2 on 2023-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='location',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='availabality',
        ),
        migrations.AddField(
            model_name='blog',
            name='availabality',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='location',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
