# Generated by Django 4.2.2 on 2023-09-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='applicantName',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='supplierName',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
