# Generated by Django 4.2.2 on 2023-09-18 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='stratOfUse',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
