# Generated by Django 4.2.2 on 2023-08-01 17:35

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='availabalityEnd',
            field=models.DateTimeField(default=blog.models.oneDayHence, validators=[django.core.validators.MinValueValidator(limit_value=blog.models.oneDayHence)]),
        ),
    ]
