# Generated by Django 4.2.2 on 2023-07-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Carpentry work', 'Carpentry work'), ('Secondary work', 'Secondary work'), ('Finishing work', 'Finishing work'), ('Motoculture maintenance', 'Motoculture maintenance'), ('Green space maintenance', 'Green space maintenance'), ('Other', 'Other')], max_length=128),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
