# Generated by Django 4.2.2 on 2023-08-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='test',
            new_name='match',
        ),
    ]
