# Generated by Django 4.2.2 on 2023-09-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contract_stratofuse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='stratOfUse',
            new_name='startOfUse',
        ),
    ]
