# Generated by Django 4.2.2 on 2023-09-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contract_applicantsignatureimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='applicantSignatureImage',
            new_name='applicantSignature',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='supplierSignatureImage',
            new_name='supplierSignature',
        ),
    ]
