# Generated by Django 4.2.2 on 2023-09-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contract_applicantsignature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='applicantSignature',
            new_name='applicantSignatureImage',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='supplierSignature',
            new_name='supplierSignatureImage',
        ),
    ]
