# Generated by Django 4.2.2 on 2023-09-13 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_applicantsignatureimage_contract_applicantsignature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='approvalDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
