# Generated by Django 4.2.2 on 2023-09-18 09:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_stratofuse_contract_startofuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='endOfUse',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
        migrations.AlterField(
            model_name='contract',
            name='startOfUse',
            field=models.DateField(default=datetime.date.today, validators=[django.core.validators.MinValueValidator(limit_value=datetime.date.today)]),
        ),
    ]
