# Generated by Django 4.2.2 on 2023-09-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_rename_applicantsignature_contract_applicantsignatureimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='approvalDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierApproval',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierName',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierPostalAddress',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierSignatureImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
