# Generated by Django 4.2.2 on 2023-09-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_contract_endofuse_alter_contract_startofuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='applicantSignature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='applicant_signature', to='blog.signaturemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierApproval',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierName',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='supplierPostalAddress',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
