# Generated by Django 4.2.2 on 2023-09-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='starred',
        ),
        migrations.AddField(
            model_name='blog',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
