# Generated by Django 4.2.2 on 2023-09-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contract_approvaldate_alter_contract_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='applicantSignatureImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
