# Generated by Django 4.2.2 on 2023-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postalAddress',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
