# Generated by Django 4.2.2 on 2023-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postalAddress',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
